version: '3.2'
services:
  go-hoover:
    image: moh90poe/go-hoover:v0.0.1
    environment:
      ROOMBA_ADDRESS: "0.0.0.0:"
      ROOMBA_PORT: 8080
      GODEBUG: "http2debug=2"
    ports:
      - 8800:8080
